name: CD Pipeline

on:
  push:
    branches:
      - master  # Adjust to your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push bot-service image
        id: bot-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./bot-service/Dockerfile
          push: true
          tags: anas1005/instruvibes:bot-service

      - name: Build and push search-service image
        id: search-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./search-service/Dockerfile
          push: true
          tags: anas1005/instruvibes:search-service

      - name: Build and push converter-service image
        id: converter-service
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./converter-service/Dockerfile
          push: true
          tags: anas1005/instruvibes:converter-service  

      - name: SSH into EC2 and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          env:
            TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
            SPOTIFY_ID: ${{ secrets.SPOTIFY_ID }}
            SPOTIFY_SECRET: ${{ secrets.SPOTIFY_SECRET }}
            YOUTUBE_API: ${{ secrets.YOUTUBE_API }}
            GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          script: |
            cd /home/ubuntu/Instruvibes
            sudo docker-compose -f docker-compose.prod.yml pull
            sudo docker-compose -f docker-compose.prod.yml up -d
